// Fill out your copyright notice in the Description page of Project Settings.

#include "BotBehaviorProfile.h"
#include "UnrealNetwork.h"


void UBotBehaviorProfile::GetLifetimeReplicatedProps(TArray< FLifetimeProperty > & OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(UBotBehaviorProfile, DefaultTeam)
		DOREPLIFETIME(UBotBehaviorProfile, FriendlyFireVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, HurtHelpVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, WasDisarmedHelpVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, DisarmedLaughVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, ThanksOnAssistVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, RespectOnKillVoiceChance)
		DOREPLIFETIME(UBotBehaviorProfile, IgnoreEnemiesWithAllyCount)
		DOREPLIFETIME(UBotBehaviorProfile, RangedAccuracyDegreesMinMax)
		DOREPLIFETIME(UBotBehaviorProfile, RangedAccuracyDistanceMinMax)
		DOREPLIFETIME(UBotBehaviorProfile, bPrefersAltMode)
		DOREPLIFETIME(UBotBehaviorProfile, BaseAttackHesitanceTime)
		DOREPLIFETIME(UBotBehaviorProfile, AttackHesitanceVariance)
		DOREPLIFETIME(UBotBehaviorProfile, RegularAttackProbability)
		DOREPLIFETIME(UBotBehaviorProfile, FootworkInsteadOfParryProbability)
		DOREPLIFETIME(UBotBehaviorProfile, FootworkWithCrouchProbability)
		DOREPLIFETIME(UBotBehaviorProfile, ParryTimingVariance)
		DOREPLIFETIME(UBotBehaviorProfile, PerfectParryProbability)
		DOREPLIFETIME(UBotBehaviorProfile, FeintTimingVariance)
		DOREPLIFETIME(UBotBehaviorProfile, FallForFeintProbability)
		DOREPLIFETIME(UBotBehaviorProfile, ComboProbability)
		DOREPLIFETIME(UBotBehaviorProfile, DragProbability)
		DOREPLIFETIME(UBotBehaviorProfile, AccelProbability)
		DOREPLIFETIME(UBotBehaviorProfile, ChamberProbability)
		DOREPLIFETIME(UBotBehaviorProfile, MorphProbability)
		DOREPLIFETIME(UBotBehaviorProfile, GambleProbability)
		DOREPLIFETIME(UBotBehaviorProfile, FeintProbability)
		DOREPLIFETIME(UBotBehaviorProfile, RiposteProbability)
		DOREPLIFETIME(UBotBehaviorProfile, BrawlProbability)
		DOREPLIFETIME(UBotBehaviorProfile, MaxTurnRate)
		DOREPLIFETIME(UBotBehaviorProfile, MaxLookUpRate)
		DOREPLIFETIME(UBotBehaviorProfile, Random2DUnitVector)
		DOREPLIFETIME(UBotBehaviorProfile, bWillBrawl)
		DOREPLIFETIME(UBotBehaviorProfile, bWillRegularAttack)
		DOREPLIFETIME(UBotBehaviorProfile, bWillRiposte)
		DOREPLIFETIME(UBotBehaviorProfile, bWillFeint)
		DOREPLIFETIME(UBotBehaviorProfile, bWillGamble)
		DOREPLIFETIME(UBotBehaviorProfile, bWillMorph)
		DOREPLIFETIME(UBotBehaviorProfile, bWillChamber)
		DOREPLIFETIME(UBotBehaviorProfile, bWillAccel)
		DOREPLIFETIME(UBotBehaviorProfile, bWillDrag)
		DOREPLIFETIME(UBotBehaviorProfile, bWillCombo)
		DOREPLIFETIME(UBotBehaviorProfile, bWillFallForFeint)
		DOREPLIFETIME(UBotBehaviorProfile, FeintTimingRandom)
		DOREPLIFETIME(UBotBehaviorProfile, bWillPerfectParry)
		DOREPLIFETIME(UBotBehaviorProfile, ParryTimingRandom)
		DOREPLIFETIME(UBotBehaviorProfile, bWillFootwork)
		DOREPLIFETIME(UBotBehaviorProfile, bWillFootworkWithCrouch)
		DOREPLIFETIME(UBotBehaviorProfile, AttackHesitanceRandom)
}