#pragma once

#include "CoreMinimal.h"
#include "Mordhau.h"
#include "CharacterMeshComponent.h"
#include "HumanMeshComponent.generated.h"

/**
*
*/
UCLASS(Blueprintable, ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class MORDHAU_API UHumanMeshComponent : public UCharacterMeshComponent {
	GENERATED_BODY()
public:
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class USkeletalMesh* FPMesh; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class USkeletalMesh* FPDeadMesh; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class USkeletalMesh* UnifiedMesh; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, Export, VisibleAnywhere)
	TArray<class ULODSkeletalMeshComponent*> SlaveSkeletalMeshComponents; //(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float ClothBlendWeightInterpSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector2D FOVLODDistanceScaleIn; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector2D FOVLODDistanceScaleOut; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	bool bForceInstantMeshUpdate; //(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	float UnifiedMeshDistance; //(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	float SeparatedMeshDistance; //(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TArray<float> LODIncreaseDistance; //(Edit, BlueprintVisible, ZeroConstructor)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TArray<float> LODDecreaseDistance; //(Edit, BlueprintVisible, ZeroConstructor)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int CurrentForcedLOD; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	bool bMeshesAreInitialized; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	bool bMaterialsAreInitialized; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bHasInvisibleBody; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TArray<class USkeletalMesh*> OverrideMeshConstructionParts; //(Edit, BlueprintVisible, ZeroConstructor)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	EWearableSlot SingleSlotMode; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UClass* SingleSlotModeWearableToUse; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeleton* BodySkeleton; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UPhysicsAsset* ShadowPhysicsAsset; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HelmetAOOffset; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HelmetAOPower; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HelmetAOIntensity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HelmetAOEyeIntensity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UMaterialInterface* LODMasterMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* HelmetCoifMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* ChestShouldersMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* ArmsGlovesMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* LowerChestMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* LegsBootsMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* HelmetCoifChestMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* LegsBootsChestLowMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class UMaterialInterface* ArmsGlovesShouldersMaterial; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* Eyes; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* FemaleEyes; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftArm; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftArm1P; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightArm; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightArm1P; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftHand; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftHand1P; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightHand; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightHand1P; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftLeg; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightLeg; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* LeftFoot; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* RightFoot; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly)
	class USkeletalMesh* Torso; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector ArmsBouncyLimits; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector SpineBouncyLimits; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector BreastBouncyLimits; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector BellyBouncyLimitsFat; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector BellyBouncyLimitsSlim; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	struct FVector LegsBouncyLimits; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bDisableBouncy; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TArray<class UAnimMontage*> UnarmedPreviewPoses; //(Edit, BlueprintVisible, ZeroConstructor)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UBlendSpaceBase* UnarmedUpperBlendSpace1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedUpperAdditive1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UBlendSpaceBase* UnarmedUpperBlendSpace; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedUpperAdditive; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedLowerAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedJumpAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedLandAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedFallingAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedJumpAnimation1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedLandAnimation1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* UnarmedFallingAnimation1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UBlendSpaceBase* HorseUnarmedUpperBlendSpace1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedUpperAdditive1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UBlendSpaceBase* HorseUnarmedUpperBlendSpace; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedUpperAdditive; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedRearing; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedRearing1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedJump; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequence* HorseUnarmedJump1P; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimMontage* InteractWithAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimMontage* InteractWith1PAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UAnimSequenceBase* StunAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bIgnoreAngularVelocityAnimation; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	class UCurveFloat* RiposteBlendInCurve; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	

	
	UFUNCTION(BlueprintCallable)	
	void UpdateSkeletalMeshComponentMaterials(class USkeletalMeshComponent* USMC);
	UFUNCTION(BlueprintCallable)
	void UpdateAllSkeletalMeshComponentMaterials();
	UFUNCTION(BlueprintCallable)
	void SetMaterialParamsForMergedSlot(const FString& Prefix, class UMordhauWearable* Wearable, class UMaterialInstanceDynamic* Mid);
	UFUNCTION(BlueprintCallable)
	void SetMaterialParamsForLODMasterSlot(const FString& Slot, class UMordhauWearable* Wearable, class UMaterialInstanceDynamic* Mid);
	UFUNCTION(BlueprintCallable)
	void OnCharacterTornOff(class AAdvancedCharacter* Character);
	UFUNCTION(BlueprintCallable)
	void OnCharacterChangedTeam(class AAdvancedCharacter* Character);
	UFUNCTION(BlueprintCallable)
	void OnCharacterCameraStyleChanged(class AMordhauCharacter* Character);
	UFUNCTION(BlueprintCallable)
	void OnCharacterBuilt(class AMordhauCharacter* Character);
	UFUNCTION(BlueprintCallable)
	bool CreateUnifiedMeshIfNone(bool bRequireHeavyDutyCheck);
	UFUNCTION(BlueprintCallable)
	bool CreateFPMeshIfNone();
	UFUNCTION(BlueprintCallable)
	bool CreateFPDeadMeshIfNone();
};
