// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "CreatureAnimInstance.h"
#include "Mordhau.h"
#include "Runtime/Engine/Classes/Kismet/KismetMathLibrary.h"
#include "MordhauAnimInstance.generated.h"

/**
*
*/
USTRUCT(BlueprintType)
struct FFacialBoneSetup
{
	GENERATED_BODY()
public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FName BoneName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FName SelectionBoneOverride;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsSymmetrical;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SelectionBiasFactor;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<FName> ChildBones;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int Level;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int SymmetryTwinBoneIndex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FName SymmetryTwinBoneName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int BoneIndex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D TranslateXRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D TranslateYRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D TranslateZRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D ScaleXRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D ScaleYRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D ScaleZRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D RotateXRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D RotateYRange;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D RotateZRange;
};
/*USTRUCT(BlueprintType)
struct FFloatSpringState
{
GENERATED_BODY()
};*/
USTRUCT(BlueprintType)
struct FAnimNodePackedDismemberment
{
	GENERATED_BODY()
public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<int> DismemberedBonesIndices;
};
USTRUCT(BlueprintType)
struct FAnimNodePackedFaceCustomization
{
	GENERATED_BODY()
public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<struct FFacialBoneSetup> FaceCustomizationSetup;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<struct FTransform> FaceCustomizationBonesTransforms;
};
UCLASS(Blueprintable)
class MORDHAU_API UMordhauAnimInstance : public UCreatureAnimInstance
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int CreatedFrame; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int LastUpdateFrame; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float InternalScaledTimeSeconds; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float MeshRelativeZScale; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FAnimNodePackedFaceCustomization FaceCustomization; //(BlueprintVisible, BlueprintReadOnly)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FAnimNodePackedDismemberment Dismemberment; //(BlueprintVisible, BlueprintReadOnly)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TWeakObjectPtr<class AMordhauEquipment> PreviousRightHandEquipment; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TWeakObjectPtr<class AMordhauEquipment> MainEquipmentPtr; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FName MainAnimationType; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bWasRagdollFalling; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float LastRagdollFallingTime; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Force1PMeshCorrectionWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bShouldPerformInstantAnimSwitch; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsGetUpFront; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float GetUpAnimationDuration; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator GetUpRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		uint8 DeathSyncedRandom; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsDedicatedServer; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AnimLOD0; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AnimLOD1; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float RecentlyRendered; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float RecentlyRenderedNonAuth; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AnimLOD0Distance; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AnimLOD1Distance; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsFemale; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsClimbingA; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbOffsetA; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbOffsetEndOffsetA; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbLedgeOffsetA; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsSlowClimbingA; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator ClimbRotationA; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsClimbingB; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbOffsetB; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbOffsetEndOffsetB; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector ClimbLedgeOffsetB; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator ClimbRotationB; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsSlowClimbingB; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FastSmoothedIsCrouching; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float UnclampedFastSmoothedIsCrouching; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FFloatSpringState CrouchSpringState;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float ServerCrouchSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D CrouchSpringLimits; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float CrouchSpringStiffness; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float UncrouchSpringStiffness; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float CrouchSpringDamping; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float CrouchSpringMass; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* VehicleTransitionAnimation; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleTransitionBlendWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleTransitionComponentLocation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleTransitionComponentRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsDrivingFloat; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LowerBodyRotationOffset; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Direction; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator MovementCorrectionHips; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float MovementCorrectionHipsInterpSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float MovementCorrectionAnimRate; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DirectionWithOffset; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DirectionOffset; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DirectionOffsetSlowInterpSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DirectionOffsetSlow; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Velocity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SmoothedVelocity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float OneToZeroAtWalkSpeed; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AnimRateFactor1PMaxSprint; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float MovementSpeedScale; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float MovementAnimRate; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SpeedWarping; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float ThirdPersonVelocity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bUseBackBlendSpace; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator StopBounce; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator StopBounceWorld; //(IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float StopBounceLimit; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D BounceInterpSpeedIn; //(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D BounceInterpSpeedOut; //(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector BounceDuck; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BounceDuckLimit; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SlowVelocityLagTime; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FastVelocityLagTime; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float StopTiltFactor; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float StopDuckFactor; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AngularVelocityInterpSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AngularVelocity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AbsoluteAngularVelocityLowerBody; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AngularVelocityLowerBody; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AngularVelocityLowerBodyWindow; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector AnimatedMovementDirectionInCompSpace; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AngularVelocityPitch; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D SpringPitchYawValue; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FFloatSpringState PitchSpringState;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FFloatSpringState YawSpringState;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D SpringPitchYawStiffness; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D SpringPitchYawDamping; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D SpringPitchYawMass; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HandSpringWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsFirstPerson; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsFirstPersonFloat; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsNotFirstPersonFloat; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector CameraCollisionOffset; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FTransform RightWeaponBoneBaseTransform; //(Edit, BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector WeaponSlideVector; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector WeaponSlideVectorInverse; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float WeaponSlideCompensationWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector RightShoulderOffset1P; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LeftShoulderOffset1P; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float ShoulderOffset1PWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LeftShoulderIdleOffset1P; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector RightHandIKOffset; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float RightHandIKOffsetWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float OffhandIKWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FTransform OffhandSlidingAxis; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsOffhandFixedTarget; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector OffhandFixedTargetVector; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LeftHandGripPosition; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector RightHandGripPosition; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator RightHandGripRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float OffhandIsRightHand; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* JumpAnimation; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* FallingAnimation; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* LandAnimation; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyMagnitudeOffset; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncySlowVelocityLagTime; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyFastVelocityLagTime; //(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* SkinnyPose; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* FatPose; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* StrongPose; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyInterpSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyFactorBreasts; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyFactorArms; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyFactorBelly; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BouncyFactorLegs; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector BreastsT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LowerBackBellyT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector SpineAdjustT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LeftArmAdjustT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector RightArmAdjustT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LeftUpLegAdjustT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector RightUpLegAdjustT; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsTankFloat; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsDwarfFloat; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DwarfSlowerAnimSpeedFactor; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Fat; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Skinny; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Strong; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsHeadDismembered; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator NeckDismemberedRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LeftShoulderDismemberedRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsLeftArmDismembered; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator RightShoulderDismemberedRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsRightArmDismembered; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float IsAnythingDismembered; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float TrackingWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LookingAtRotationNeck; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LookingAtRotationHead; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LookingAtRotationEyes; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HideEars; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HideNose; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UCurveFloat* BreathCurve; //(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector2D HealthToBreathDuration; //(Edit, DisableEditOnInstance, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Breath; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float CounterCompensateLookWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator CounterCompensateRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float LookUpValue; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float RightLegBendBlendWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SpineBendBlendWeight; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SpineArmsCompensationFactor; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float TurnValue; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float LeftHandIsEmpty; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AtmosphericsWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Arms3PSyncWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float BlockDirection; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float DisarmDirection; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FSpineSpaceAdditive SpineSpaceAdditive; //(BlueprintVisible)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float LeftTorsoBlendWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* AttackBounce; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* RangedDrawnAdditive; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator SwayRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float SwayWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* ParryAdditive; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* ParryPushAdditive; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* AltParryPushAdditive; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float LowerBodyBlendSpaceBlendTime; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* UpperBlendSpaceA; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float UpperBlendSpaceABlendTime; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* UpperAdditiveA; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UBlendSpaceBase* UpperBlendSpaceB; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float UpperBlendSpaceBBlendTime; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* UpperAdditiveB; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsCurrentUpperA; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* LowerBodyAnimationA; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* LowerBodyAnimationB; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		class UAnimSequence* HorseUpperRearing; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsCurrentLowerA; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bIsHorseRearing; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Couching; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Rearing; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Lean; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleAnimTime; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleAnimRate; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleLeftHandTarget; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleRightHandTarget; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleTurn; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleLookUp; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleLeftFootTarget; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleRightFootTarget; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleLeftFootRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleRightFootRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleVelocity; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float VehicleDirection; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector VehicleSeat; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleActorRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleRotationOffset; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator VehicleSeatRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bBallistaReloading; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HitEffectIKWeight; //(BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HitEffectLocationSlideSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float HitEffectDisableSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector HitEffectIKLocation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector HitEffectIKLocationStart; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator HitEffectRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator HitEffectRotationStart; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchFreezeBlendInDuration; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchFreezeRotationBlendInSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchFreezeTranslationBlendInSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchFreezeBlendInAlpha; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchBlendInDuration; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchRotationBlendInSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchTranslationBlendInSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchRotationBlendOutSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchTranslationBlendOutSpeed; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchRotationBlendOutSpeedFast; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchTranslationBlendOutSpeedFast; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchPitchAmount; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchYawAmount; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchPitchYawFactor; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchHipsZFactor; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float WeaponDirHipsZFactor; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float TranslationNonHipsFactor; //(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator FlinchRotationTarget; //(IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector FlinchTranslationTarget; //(IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector FlinchHipsTranslationTarget; //(IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int FlinchHitSpineIdx; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float FlinchStartTime; //(ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator CurrentFlinchSpineRotationsCombined; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator HipsFlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector HipsFlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector HipsFlinchTranslationInternal; //(IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator LowerBackFlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector LowerBackFlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator SpineFlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector SpineFlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Spine1FlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Spine1FlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator NeckFlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector NeckFlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator HeadFlinchRotation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector HeadFlinchTranslation; //(BlueprintVisible, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_WeaponSlideVectorIsNonzero; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_UBCrouchAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_LBCrouchAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBCrouchSpine; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBCrouchForearms; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBCrouchArms; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBCrouchHead; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBCrouchShoulder; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_UBSpineArmsCompensationAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_UBSpineArmsCompensationRotator; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bHelper_LBFootShuffling; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_LBFootShufflingPlayRate; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bHelper_LBFootShufflingRight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_LBDirectionOffsetSlowRotator; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_LBDirectionOffsetSlowRotatorInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_LBDirectionOffsetSlowHipsZ; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_LBDirectionOffsetSlowHipsZInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_LBDirectionOffsetSlowFootRotationOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_UBVelocity; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool bHelper_LBVelocityIsZero; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_LBCrouchOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_LBCrouchOffsetInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_LBHipsZOverrideAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_TrackingWeightAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_BreathAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_IsNotDrivingFloat; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_IsAnyFlinchValueNonZero; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_HipsFlinchTranslationInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_HipsFlinchRotationInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_ArmsShoulderFlinchInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_FirstPersonNotDead; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_FirstPersonZoomOffsetAndCollision; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_CameraCollisionOffsetWithNot3PArmsSync; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_FirstPersonNotDeadWith3PArmsSync; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_IsNotFemale; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_SpineBendBlendWeightHalf; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_SpineBendBlendWeightThird; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_GroundingRightFootRotationOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_GroundingLeftFootRotationOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_GroundingRightFootTranslationOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_GroundingLeftFootTranslationOffset; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float NotFirstPersonWithAtmospherics; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float NotFirstPersonWithAtmosphericsAndAnimLOD1; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_FaceUpperLids; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_LeftHandIKWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_RightHandIKWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_RootRotationOffsetInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_StopBounceMediumWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_StopBounceLightWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_StopBounceInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_StopBounceHips; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_BounceDuckWithBounceWeight; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_BounceDuckWithBounceWeightInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_SpineBendRotation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_HipsBendRotation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_SpineBendRotationAlpha; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_RightLegBendRotation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_ArmsBendRotation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float AtmosphericsWeightWithAnimLOD0; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_LowerBodyRotationOffsetInverse; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FVector Helper_RightWeaponBoneBaseTranslation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_RightWeaponBoneBaseRotation; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		struct FRotator Helper_SpringPitchYawValueRotator; //(BlueprintVisible, BlueprintReadOnly, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_HandSpringWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_ShoulderOffset1PWith1PWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float Helper_JiggleBouncyWeight; //(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
};
